### ISSUE TITLE
Get an error when training

### ISSUE THREAD

**Issue by shenxuhui** [kaituoxu/X-Punctuator#3]
Namespace(batch_size=5, bidirectional=1, checkpoint=0, continue_from='', early_stop=0, embedding_dim=256, epochs=30, half_lr=0, hidden_size=512, l2=0.0, lr=0.001, max_norm=5, model_path='final.pth.tar', num_class=5, num_embeddings=5002, num_layers=2, num_workers=1, print_freq=1, punc_vocab='data/punc_vocab', save_folder='exp/temp', train_data='data/train20', use_cuda=0, valid_data='data/train20', visdom=0, visdom_epoch=0, visdom_id='X-Punctuator training', vocab='data/vocab')
LstmPunctuator(
  (embedding): Embedding(5002, 256)
  (lstm): LSTM(256, 512, num_layers=2, batch_first=True, bidirectional=1)
  (fc): Linear(in_features=1024, out_features=5, bias=True)
)
Number of parameters: 10739205
Training...
Traceback (most recent call last):
  File "/pkwork2/xhs92/task1.2/X-Punctuator/egs/toy/../../src/bin/train.py", line 84, in <module>
    main(args)
  File "/pkwork2/xhs92/task1.2/X-Punctuator/egs/toy/../../src/bin/train.py", line 78, in main
    solver.train()
  File "/pkwork2/xhs92/task1.2/X-Punctuator/src/solver/solver.py", line 77, in train
    tr_avg_loss = self._run_one_epoch(epoch)
  File "/pkwork2/xhs92/task1.2/X-Punctuator/src/solver/solver.py", line 181, in _run_one_epoch
    pred = self.model(padded_input, input_lengths)
  File "/restools/tools/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/pkwork2/xhs92/task1.2/X-Punctuator/src/model/model.py", line 43, in forward
    packed_output, _ = self.lstm(packed_input)
  File "/restools/tools/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/restools/tools/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
TypeError: lstm() received an invalid combination of arguments - got (Tensor, Tensor, tuple, list, bool, int, int, bool, int), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, tuple, list, bool, int, int, bool, int)
 * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, tuple, list, bool, int, int, bool, int)

**Comment by shenxuhui** [comment]
When running X-Punctuator/egs/toy/run.sh, I got the error report above. sorry to bother you, thanks for your wonderful project!

**Comment by shenxuhui** [comment]
find solution!

**Comment by shenxuhui** [comment]
find solution
